version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "7700:7700"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development

  whisper:
    build:
      context: .
      dockerfile: Dockerfile.whisper
    ports:
      - "9000:9000"
